### ISSUE TITLE
upgrade r10k

### ISSUE THREAD

**Issue by jantman** [jantman/vagrant-r10k#13]
We're using r10k 1.2.1; 1.5.1 is out. We should upgrade. There may have been some changes that affect us.

**Comment by cdenneen** [comment]
2.x is out now

**Comment by jantman** [comment]
@cdenneen yeah, I know... I haven't looked to see how difficult the switch will be. I'll do my best to get to this sometime soon, but I've been pretty swamped and also pretty busy in my personal life.

**Comment by jantman** [comment]
Upgraded to 1.5.1 in #34 / #35. I'll leave this open to investigate 2.0.0.

Many thanks to @cdenneen for the 1.5 upgrade work!

**Comment by jantman** [comment]
@cdenneen 0.4.0 is live on rubygems.org. Thanks!

**Comment by cdenneen** [comment]
Thanks. Sadly r10k 2.1.0 was released and have to play catchup yet again :-(
Hopefully with your modifications for 1.5.1 2.0.x and 2.1.x will be easier
(2.0.x was a backwards compatible release so should work)
