### ISSUE TITLE
Problems with plugin sync

### ISSUE THREAD

**Issue by frizop** [jantman/vagrant-r10k#2]
When trying to launch a `vagrant up` and using config elements like the following, I get the error in the debug log  -

    config.r10k.puppet_dir = "."
    config.r10k.puppetfile_path = "Puppetfile"
    config.r10k.module_path = "modules"

and the following Puppetfile

    mod 'puppetlabs/ntp'
    mod 'basti1302/windows_path'
    mod 'rismoney/chocolatey'

The short of the error is the following

    [R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x00000102150498> failed while running: Command puppet module --modulepath
    /Users/frizop/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1:
    /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in 
    `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

So I'm pretty confused here, if I manually run the puppet module command above it works fine, if I run `r10k puppetfile install` it installs fine, but for some reason (even after uninstalling and reinstalling the vagrant r10k plugin) it still doesn't work, any help?

And the debug log:

        DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
    DEBUG subprocess: Exit status: 0
     INFO warden: Calling OUT action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x000001024a7a88>
     INFO runner: Preparing hooks for middleware sequence...
     INFO runner: 5 hooks defined.
     INFO runner: Running action: #<Vagrant::Action::Warden:0x00000102540f30>
     INFO warden: Calling IN action: #<Proc:0x0000010258bb98@/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:94 (lambda)>
     INFO warden: Calling IN action: #<Proc:0x00000102540e90@/Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:94 (lambda)>
     INFO warden: Calling IN action: #<VagrantPlugins::R10k::Modulegetter:0x0000010207aca8>
     INFO interface: info: vagrant-r10k: Beginning r10k deploy of puppet modules into /Users/User1/Documents/vagrant-windows/modules using /Users/User1/Documents/vagrant-windows/Puppetfile
     INFO interface: info: ==> build: vagrant-r10k: Beginning r10k deploy of puppet modules into /Users/User1/Documents/vagrant-windows/modules using /Users/User1/Documents/vagrant-windows/Puppetfile
    ==> build: vagrant-r10k: Beginning r10k deploy of puppet modules into /Users/User1/Documents/vagrant-windows/modules using /Users/User1/Documents/vagrant-windows/Puppetfile
    [R10K::Task::Puppetfile::Sync - INFO] Loading modules from Puppetfile into queue
    [R10K::Task::Module::Sync - INFO] Deploying chocolatey into /Users/User1/Documents/vagrant-windows/modules
    [R10K::Task::Module::Sync - INFO] Deploying windows_path into /Users/User1/Documents/vagrant-windows/modules
    [R10K::Task::Module::Sync - INFO] Deploying ntp into /Users/User1/Documents/vagrant-windows/modules
    [R10K::Module::Forge - DEBUG] Execute: puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp
    [R10K::Module::Forge - DEBUG] [puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp] STDERR: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'
    [R10K::TaskRunner - ERROR] Task #<R10K::Task::Module::Sync:0x00000102447048> failed while running: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

    [R10K::Task::Puppetfile::Purge - DEBUG] No stale modules in /Users/User1/Documents/vagrant-windows/modules
    ERROR warden: Error occurred: RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

     INFO warden: Beginning recovery process...
     INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x0000010207ae10>
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Recovery complete.
    ERROR warden: Error occurred: RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
    ERROR warden: Error occurred: RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO warden: Beginning recovery process...
     INFO warden: Recovery complete.
     INFO environment: Released process lock: machine-action-7158750c4ad0798b640156d433f681aa
     INFO environment: Running hook: environment_unload
     INFO runner: Preparing hooks for middleware sequence...
     INFO runner: 5 hooks defined.
     INFO runner: Running action: #<Vagrant::Action::Builder:0x0000010265b848>
    ERROR vagrant: Vagrant experienced an error! Details:
    ERROR vagrant: #<VagrantPlugins::R10k::ErrorWrapper: RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'
    >
    ERROR vagrant: RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

    ERROR vagrant: /Users/User1/.vagrant.d/gems/gems/vagrant-r10k-0.1.1/lib/vagrant-r10k/modulegetter.rb:113:in `block in call'
    /Users/User1/.vagrant.d/gems/gems/vagrant-r10k-0.1.1/lib/vagrant-r10k/modulegetter.rb:112:in `each'
    /Users/User1/.vagrant.d/gems/gems/vagrant-r10k-0.1.1/lib/vagrant-r10k/modulegetter.rb:112:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builtin/call.rb:53:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/warden.rb:34:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/builder.rb:116:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `block in run'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/util/busy.rb:19:in `busy'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/action/runner.rb:66:in `run'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:196:in `action_raw'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:173:in `block in action'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/environment.rb:474:in `lock'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `call'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/machine.rb:161:in `action'
    /Applications/Vagrant/embedded/gems/gems/vagrant-1.6.5/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
    /Applications/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
    /Applications/Vagrant/embedded/gems/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
     INFO interface: error: RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

    RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
    	from /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'

     INFO interface: Machine: error-exit ["VagrantPlugins::R10k::ErrorWrapper", "RuntimeError: Command puppet module --modulepath /Users/User1/Documents/vagrant-windows/modules install --force puppetlabs/ntp exited with 1: /Applications/Vagrant/embedded/gems/gems/bundler-1.6.6/lib/bundler/rubygems_integration.rb:256:in `block in replace_gem': puppet is not part of the bundle. Add it to Gemfile. (Gem::LoadError)\n\tfrom /usr/local/var/rbenv/versions/2.0.0-p247/bin/puppet:22:in `<main>'\n"]
    [User1@profail]~/Documents/vagrant-windows%

**Comment by tremblaysimon** [comment]
I've got a similar error and what I understand it is we can't have puppet and puppet gem installed at the same time? 

The workaround for me is to avoid using Puppet Forge directly.

**Comment by jantman** [comment]
@tremblaysimon The puppet gem isn't included in this plugin as doing so can cause conflicts on systems where Puppet is already installed (i.e. via os packages).

For the time being, yes, if you specify the modules directly from git or other source control (instead of as forge modules), it will prevent this issue.

**Comment by lorello** [comment]
I've got the same problem, having three versions of puppet installed (3.6.2, 3.7.4, 3.7.5) with rubygem.

I've removed them and installed 3.7.5 from the puppetlabs debian repo, the problem disappeared.

Thanks
L

**Comment by frizop** [comment]
@lorello I was using gems as well but ended up giving up and just installing the packages from puppetlans directly, no more problems. I'd love to know why but I don't have the time to debug this or really worry about it.

**Comment by mmarod** [comment]
Er so... If I am understanding this thread correctly -- Forge modules cannot be referenced from a Puppetfile still? I'm having this issue and do not want to reference the git repos directly. I have one version of the puppet gem (4.2.0) installed on my OSX 10.10.3 host.

**Comment by mmarod** [comment]
I seem to have been able to get it to work by doing..

```
vagrant plugin install puppet
```

Sorry for the interruption!

**Comment by jantman** [comment]
@mmarod, I'd completely forgotten that you can use `vagrant plugin install` to install any Gem into Vagrant's environment... thanks so much for reminding me of this. I'll update the docs and make sure a note is included in the next release (which should be coming soon, hopefully).
