### ISSUE TITLE
Modules from svn copied twice

### ISSUE THREAD

**Issue by Robbe64** [jantman/vagrant-r10k#8]
If I add a module in the Puppetfile which is located in a svn repository the module is checked out twice.
First in the defined module_path and second in dhe puppet_dir.

My r10k config in the Vagrantfile contains this:
	config.r10k.puppet_dir = "."
	config.r10k.puppetfile_path = "Puppetfile"
	config.r10k.module_path = "r10k_modules/"

**Comment by jantman** [comment]
Hmm... the multiple deploys issue is related to #1 in https://github.com/jantman/vagrant-r10k/issues/7#issuecomment-91508411 but I've never seen it do that in two __different__ directories before. I'll dig into this later today. Thanks for reporting it.

@Robbe64 if you don't mind, could you please confirm your Vagrant, Ruby and OS versions, and also run that command (``vagrant up`` I assume) prefixed with ``VAGRANT_LOG=debug`` and post the output in a gist? Thanks.

**Comment by Robbe64** [comment]
I'm using windows 7, ruby 2.2.0, Vagrant 1.7.2
I will add the logfile later.

**Comment by jantman** [comment]
@Robbe64 also, what virtualization provider are you using? If you could upload your Vagrantfile (with any confidential information removed), it might prove helpful.

**Comment by Robbe64** [comment]
I'm using VirtualBox 4.3.22.

My Vagrantfile:
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu1404"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.vm.network "private_network", ip: "192.168.50.4"
  

	# https://github.com/jantman/vagrant-r10k
	config.r10k.puppet_dir = "."
	config.r10k.puppetfile_path = "Puppetfile"
	config.r10k.module_path = "r10k_modules/"
  
  config.vm.provision "puppet" do |puppet|
     puppet.manifests_path = "."
     puppet.manifest_file  = "init.pp"
     puppet.module_path = ["../modules/", "r10k_modules/"] 
     puppet.facter = {
      # Specifying the proxy environment variables this way is a work around.  
      # The work around can be removed when this issue is fixed https://github.com/mitchellh/vagrant/issues/2270
      "anything=anything http_proxy=http://192.168.50.1:3128 https_proxy=http://192.168.50.1:3128 anything" => "anything"
    }
  end
end

**Comment by jantman** [comment]
@Robbe64 would it be possible to get that debug-level logfile, preferably in a clean environment (i.e. none of the r10k-managed modules checked out yet)?

**Comment by jantman** [comment]
This should be fixed by #9 / #23 though they're not released yet. I've also added an [acceptance test](https://github.com/jantman/vagrant-r10k/blob/816d07a209f46cc7443af5bf57a579b574a65061/spec/acceptance/vagrant-r10k/vagrant-r10k_spec.rb#L187) for it.
